CREATE PROCEDURE [dbo].[BookingEntries_GetBySCAVersionId]
@SCAVersionId INT
AS
BEGIN
	SET NOCOUNT ON;
	SELECT [BookingEntryId]
      ,[SCAVersionId]
      ,[AWB]
      ,[BookingCreatedDate]
      ,[FlightDepartureDate]
      ,[BookingTime]
      ,[FlightDepartureTime]
      ,[BookingOrigin]
      ,[BookingDestination]
      ,[BookingRateType]
      ,[AgentCode]
      ,[AgentName]
      ,[BookingDestinationCountry]
      ,[BookingDestinationRegion]
      ,[BookingLastUpdatedBy]
      ,[BookingOriginCountry]
      ,[BookingOriginSalesArea]
      ,[BookingOriginRegion]
      ,[BookingReference]
      ,[Channel]
      ,[SpecialHandlingCodes]
      ,[ChargeableWeight]
      ,[Currency]
      ,[RevGBP]
      ,[RevForeign]
      ,[YieldGBP]
      ,[YieldForeign]
      ,[Volume]
      ,[ProductCode]
      ,[ProductName]
      ,[FlightNumber]
      ,[MetalInfo]
      ,[CreatedOn]
      ,[ExceptionId]
      ,[ExceptionDescription]
      ,[ExceptionRuleExist]
  FROM [dbo].[BookingEntries]
  WHERE SCAVersionId=@SCAVersionId
END