Create PROCEDURE [dbo].[SCAExceptions_Update]
			@SCAExceptionId INT
		   ,@StartDate DATETIME = NULL
           ,@EndDate  DATETIME = NULL
           ,@Description VARCHAR(MAX)=NULL
           ,@BookingOrigin VARCHAR(MAX)=NULL
           ,@BookingDestination VARCHAR(MAX)=NULL
           ,@BookingRateType VARCHAR(MAX)=NULL
           ,@AgentCode VARCHAR(MAX)=NULL
           ,@BookingDestinationCountry VARCHAR(MAX)=NULL
           ,@BookingDestinationRegion VARCHAR(MAX)=NULL
           ,@BookingOriginCountry VARCHAR(MAX)=NULL
           ,@BookingOriginSalesArea VARCHAR(MAX)=NULL
           ,@BookingOriginRegion VARCHAR(MAX)=NULL
           ,@Channel VARCHAR(MAX)=NULL
           ,@SpecialHandlingCodes VARCHAR(MAX)=NULL
		   ,@ProductCode VARCHAR(MAX)=NULL
           ,@MetalInfo VARCHAR(MAX)=NULL
           ,@ExcludeBookingOrigin VARCHAR(MAX)=NULL
           ,@ExcludeBookingDestination VARCHAR(MAX)=NULL
           ,@ExcludeBookingRateType VARCHAR(MAX)=NULL
           ,@ExcludeBookingDestinationRegion VARCHAR(MAX)=NULL
           ,@ExcludeAgentCode VARCHAR(MAX)=NULL
           ,@ExcludeBookingDestinationCountry VARCHAR(MAX)=NULL
           ,@ExcludeBookingOriginCountry VARCHAR(MAX)=NULL
           ,@ExcludeBookingOriginSalesArea VARCHAR(MAX)=NULL
           ,@ExcludeBookingOriginRegion VARCHAR(MAX)=NULL
           ,@ExcludeChannel VARCHAR(MAX)=NULL
           ,@ExcludeSpecialHandlingCodes VARCHAR(MAX)=NULL
           ,@ExcludeProductCode VARCHAR(MAX)=NULL
           ,@ExcludeMetalInfo VARCHAR(MAX)=NULL
           ,@ChargeableWeight DECIMAL(18,4)=NULL
           ,@IsChargeableWeightRange BIT=0
           ,@IsChargeableWeightLessThan BIT=0
           ,@IsChargeableWeightEqualTo BIT=0
           ,@IsChargeableWeightLessthanEqualTo BIT=0
           ,@IsChargeableWeightGreaterThan BIT=0
           ,@IsChargeableWeightGreaterThanEqualTo BIT=0
           ,@ChargeableWeightRangeFrom DECIMAL(18,4)=NULL
           ,@ChargeableWeightRangeTo DECIMAL(18,4)=NULL
           ,@Volume DECIMAL(18,4)=NULL
           ,@IsVolumeRange BIT=0
           ,@IsVolumeLessThan BIT=0
           ,@IsVolumeEqualTo BIT=0
           ,@IsVolumeLessthanEqualTo BIT=0
           ,@IsVolumeGreaterThan BIT=0
           ,@IsVolumeGreaterThanEqualTo BIT=0
           ,@VolumeRangeFrom DECIMAL(18,4)=NULL
           ,@VolumeRangeTo DECIMAL(18,4)=NULL
           ,@IsActive BIT=1
           ,@UpdatedOn  DATETIME = NULL
		   ,@UpdatedBy INT = NULL
AS
BEGIN
UPDATE [dbo].[SCAExceptions] SET
	[StartDate]=@StartDate,
	[EndDate]=@EndDate,
	[Description]=@Description,
	[BookingOrigin]=@BookingOrigin,
	[BookingDestination]=@BookingDestination,
	[BookingRateType]=@BookingRateType,
	[AgentCode]=@AgentCode,
	[BookingDestinationCountry]=@BookingDestinationCountry,
	[BookingDestinationRegion]=@BookingDestinationRegion,
	[BookingOriginCountry]=@BookingOriginCountry,
	[BookingOriginSalesArea]=@BookingOriginSalesArea,
	[BookingOriginRegion]=@BookingOriginRegion,
	[Channel]=@Channel,
	[SpecialHandlingCodes]=@SpecialHandlingCodes,
	[ProductCode]=@ProductCode,
	[MetalInfo]=@MetalInfo,
	[ExcludeBookingOrigin]=@ExcludeBookingOrigin,
	[ExcludeBookingDestination]=@ExcludeBookingDestination,
	[ExcludeBookingRateType]=@ExcludeBookingRateType,
	[ExcludeBookingDestinationRegion]=@ExcludeBookingDestinationRegion,
	[ExcludeAgentCode]=@ExcludeAgentCode,
	[ExcludeBookingDestinationCountry]=@ExcludeBookingDestinationCountry,
	[ExcludeBookingOriginCountry]=@ExcludeBookingOriginCountry,
	[ExcludeBookingOriginSalesArea]=@ExcludeBookingOriginSalesArea,
	[ExcludeBookingOriginRegion]=@ExcludeBookingOriginRegion,
	[ExcludeChannel]=@ExcludeChannel,
	[ExcludeSpecialHandlingCodes]=@ExcludeSpecialHandlingCodes,
	[ExcludeProductCode]=@ExcludeProductCode,
	[ExcludeMetalInfo]=@ExcludeMetalInfo,
	[ChargeableWeight]=@ChargeableWeight,
	[IsChargeableWeightRange]=@IsChargeableWeightRange,
	[IsChargeableWeightLessThan]=@IsChargeableWeightLessThan,
	[IsChargeableWeightEqualTo]=@IsChargeableWeightEqualTo,
	[IsChargeableWeightLessthanEqualTo]=@IsChargeableWeightLessthanEqualTo,
	[IsChargeableWeightGreaterThan]=@IsChargeableWeightGreaterThan,
	[IsChargeableWeightGreaterThanEqualTo]=@IsChargeableWeightGreaterThanEqualTo,
	[ChargeableWeightRangeFrom]=@ChargeableWeightRangeFrom,
	[ChargeableWeightRangeTo]=@ChargeableWeightRangeTo,
	[Volume]=@Volume,
	[IsVolumeRange]=@IsVolumeRange,
	[IsVolumeLessThan]=@IsVolumeLessThan,
	[IsVolumeEqualTo]=@IsVolumeEqualTo,
	[IsVolumeLessthanEqualTo]=@IsVolumeLessthanEqualTo,
	[IsVolumeGreaterThan]=@IsVolumeGreaterThan,
	[IsVolumeGreaterThanEqualTo]=@IsVolumeGreaterThanEqualTo,
	[VolumeRangeFrom]=@VolumeRangeFrom,
	[VolumeRangeTo]=@VolumeRangeTo,
	[IsActive]=@IsActive,
	[UpdatedOn]=@UpdatedOn,
	[UpdatedBy]=@UpdatedBy
	WHERE SCAExceptionId=@SCAExceptionId
	SELECT @@ROWCOUNT       
END
