
CREATE TABLE [dbo].[LastBookingVersions](
	[LastBookingVersionId] [int] IDENTITY(1,1) NOT NULL,
	[Type] [varchar](10) NULL,
	[Value] [varchar](25) NULL,
 CONSTRAINT [PK_LastBookingVersions] PRIMARY KEY CLUSTERED 
(
	[LastBookingVersionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
