CREATE TABLE [dbo].[LastBookingEntries](
[BookingEntryId] [int] IDENTITY(1,1) NOT NULL,
[AWB] [varchar](15) NULL,
[BookingLegStatus] [varchar](20) NULL,
[BookingCreatedDate] [varchar](max) NULL,
[FlightDepartureDate] [varchar](15) NULL,
[BookingTime] [varchar](max) NULL,
[FlightDepartureTime] [varchar](15) NULL,
[BookingOrigin] [varchar](max) NULL,
[BookingDestination] [varchar](max) NULL,
[BookingRateType] [varchar](max) NULL,
[AgentName] [varchar](max) NULL,
[BookingRowNumber] [varchar](max) NULL,
[BookingKey] [varchar](max) NULL,
[BookingDestinationRegion] [varchar](max) NULL,
[BookingLastUpdatedBy] [varchar](max) NULL,
[BookingLastUpdatedByGMT] [varchar](max) NULL,
[BookingOriginCountry] [varchar](max) NULL,
[BookingOriginSalesArea] [varchar](max) NULL,
[BookingOriginRegion] [varchar](max) NULL,
[BookingReference] [varchar](max) NULL,
[Channel] [varchar](max) NULL,
[SpecialHandlingCodes] [varchar](max) NULL,
[ChargeableWeight] [varchar](max) NULL,
[Currency] [varchar](max) NULL,
[RevGBP] [varchar](max) NULL,
[RevForeign] [varchar](max) NULL,
[YieldGBP] [varchar](max) NULL,
[YieldForeign] [varchar](max) NULL,
[BookingLegVolume] [varchar](max) NULL,
[Volume] [varchar](max) NULL,
[ProductCode] [varchar](max) NULL,
[ProductName] [varchar](max) NULL,
[FlightNumber] [varchar](max) NULL,
[MetalInfo] [varchar](max) NULL,
[LastBookingVersionYearId] int NOT NULL,
[LastBookingVersionMonthId] int NOT NULL,
[LastBookingVersionDayId] int NOT NULL,
[CreatedBy] [int] NOT NULL,
[CreatedOn] [datetime] NULL,
[IsConsidered] [bit] NULL,
[UpdatedBy] [int] NULL,
[UpdatedOn] [datetime] NULL,
[BookingCreatedDateTime] DATETIME NULL, 
    [FlightDepartureDateTime] DATETIME NULL, 
    PRIMARY KEY (BookingEntryId),
FOREIGN KEY (LastBookingVersionYearId) REFERENCES LastBookingVersions(LastBookingVersionId),
FOREIGN KEY (LastBookingVersionMonthId) REFERENCES LastBookingVersions(LastBookingVersionId),
FOREIGN KEY (LastBookingVersionDayId) REFERENCES LastBookingVersions(LastBookingVersionId),
FOREIGN KEY (CreatedBy) REFERENCES Users(UserId),
FOREIGN KEY (UpdatedBy) REFERENCES Users(UserId)
)