CREATE TABLE [dbo].[SCAExceptions](
	[SCAExceptionId] [int] IDENTITY(1,1) NOT NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[Description] [varchar](max) NULL,
	[BookingOrigin] [varchar](max) NULL,
	[BookingDestination] [varchar](max) NULL,
	[BookingRateType] [varchar](max) NULL,
	[AgentCode] [varchar](max) NULL,
	[BookingDestinationCountry] [varchar](max) NULL,
	[BookingDestinationRegion] [varchar](max) NULL,
	[BookingOriginCountry] [varchar](max) NULL,
	[BookingOriginSalesArea] [varchar](max) NULL,
	[BookingOriginRegion] [varchar](max) NULL,
	[Channel] [varchar](max) NULL,
	[SpecialHandlingCodes] [varchar](max) NULL,
	[ProductCode] [varchar](max) NULL,
	[MetalInfo] [varchar](max) NULL,
	[ExcludeBookingOrigin] [varchar](max) NULL,
	[ExcludeBookingDestination] [varchar](max) NULL,
	[ExcludeBookingRateType] [varchar](max) NULL,
	[ExcludeBookingDestinationRegion] [varchar](max) NULL,
	[ExcludeAgentCode] [varchar](max) NULL,
	[ExcludeBookingDestinationCountry] [varchar](max) NULL,
	[ExcludeBookingOriginCountry] [varchar](max) NULL,
	[ExcludeBookingOriginSalesArea] [varchar](max) NULL,
	[ExcludeBookingOriginRegion] [varchar](max) NULL,
	[ExcludeChannel] [varchar](max) NULL,
	[ExcludeSpecialHandlingCodes] [varchar](max) NULL,
	[ExcludeProductCode] [varchar](max) NULL,
	[ExcludeMetalInfo] [varchar](max) NULL,
	[ChargeableWeight] [decimal](18, 4) NULL,
	[IsChargeableWeightRange] [bit] NULL,
	[IsChargeableWeightLessThan] [bit] NULL,
	[IsChargeableWeightEqualTo] [bit] NULL,
	[IsChargeableWeightLessthanEqualTo] [bit] NULL,
	[IsChargeableWeightGreaterThan] [bit] NULL,
	[IsChargeableWeightGreaterThanEqualTo] [bit] NULL,
	[ChargeableWeightRangeFrom] [decimal](18, 4) NULL,
	[ChargeableWeightRangeTo] [decimal](18, 4) NULL,
	[Volume] [decimal](18, 4) NULL,
	[IsVolumeRange] [bit] NULL,
	[IsVolumeLessThan] [bit] NULL,
	[IsVolumeEqualTo] [bit] NULL,
	[IsVolumeLessthanEqualTo] [bit] NULL,
	[IsVolumeGreaterThan] [bit] NULL,
	[IsVolumeGreaterThanEqualTo] [bit] NULL,
	[VolumeRangeFrom] [decimal](18, 4) NULL,
	[VolumeRangeTo] [decimal](18, 4) NULL,
	[IsActive] [bit] NULL,
	[CreatedOn] [datetime] NULL,
	[CreatedBy] [int] NULL,
	[UpdatedOn] [datetime] NULL,
	[UpdatedBy] [int] NULL,
 CONSTRAINT [PK_SCAExceptions] PRIMARY KEY CLUSTERED 
(
	[SCAExceptionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SCAExceptions] ADD  CONSTRAINT [DF_SCAExceptions_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO
